account/urls.py
from django.contrib.auth import get_user
from django.urls import path
from account.views import *
from django.contrib.auth.decorators import login_required


app_name = 'account'
urlpatterns = [

    # path('', login_required(AccountHomeView.as_view()), name="account"),
    # path('security/', login_required(AccountSecurityView.as_view()) , name="account-security"),
    # path('settings/', login_required(AccountSettingsView.as_view()) , name="account-settings"),

]

project/urls.py
from account.views import login_view, logout_view, register_view
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rapport.urls')),

    path('login/', login_view , name="login"),
    path('logout/', logout_view , name="logout"),
    path('account/register/', register_view , name="register"),

]

rapport/urls.py
from rapport.excel import ToExcelFileView
from django.urls import path

from rapport.views import (
    RapportDeleteView,
    RapportDetailView,
    RapportFilterView,
    RapportListView,
    # RapportDetailView,
    RapportCreateView,
    RapportUpdateView,
    UserRapportListView,
    # RapportUpdateView,
    # RapportDeleteView,
)

app_name = 'rapport'
urlpatterns = [
    path('', RapportListView.as_view(), name='rapport-list'),
    path('user/rapports/<int:pk>', UserRapportListView.as_view(), name='user-rapports'),
    path('user/rapport/<int:pk>/', RapportListView.as_view(), name='rapport-list'),
    path('rapport/<int:pk>/', RapportDetailView.as_view(), name='rapport-detail'),
    path('rapport/create/', RapportCreateView.as_view(), name='rapport-create'),
    path('rapport/<int:pk>/update/', RapportUpdateView.as_view(), name='rapport-update'),
    path('rapport/<int:pk>/delete/', RapportDeleteView.as_view(), name='rapport-delete'),


    path('rapport/excel/', ToExcelFileView.as_view(), name='rapport-excel'),
    path('rapport/filter/', RapportFilterView.as_view(), name='rapport-filter'),
]

rapport/models.py
from account.models import Account
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse



# Create your models here.
class Rapport (models.Model):

    CHEF_DEP = 'CHEF_DEP'
    CHEF_SRV = 'CHEF_SRV'
    DI = 'DI'
    MAIL = 'MAIL'
    TR_INTR = 'TR_INTR'

    YEAR_IN_SCHOOL_CHOICES = [
        (CHEF_DEP, 'Par le Chef departement Informatique'),
        (CHEF_SRV, 'Par le Chef service IR&SI'),
        (DI, 'Par DI'),
        (MAIL, 'Par Mail'),
        (TR_INTR, 'Travaux Internes à La Structure'),
    ]
    author = models.ForeignKey(Account, verbose_name=_("author"), on_delete=models.CASCADE)
    date =  models.DateField(_("date"),  auto_now_add=False)
    starthour =  models.TimeField(_('start hour '))
    endhour =  models.TimeField(_('end hour '))
    title = models.TextField(_("title"))
    description = models.TextField(_("description"))
    equipment = models.TextField(_("equipment"))
    state_befor = models.TextField(_("state befor "),null=True,blank=True)
    state_after = models.TextField(_("state after "))
    device_used = models.TextField(_("Device Used"),null=True,blank=True)
    type_di = models.CharField(_("Type DI"),
        max_length=20,
        choices=YEAR_IN_SCHOOL_CHOICES,
        default=TR_INTR,
    )
    # type_di = models.TextField(_("Type DI"))
    n_di = models.TextField(_("N° DI"),null=True,blank=True)
    note = models.TextField(_("note"),null=True,blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('rapport:rapport-detail', kwargs={'pk': self.pk})

rapport/forms.py
# from rapport.models import Rapport
from django.forms import fields
from rapport.models import Rapport
from django import forms
# from category.models import Category


class RapportForm(forms.ModelForm):
    class Meta:
        model=Rapport
        fields = ['title','date','starthour','endhour', 'description','equipment','state_befor','state_after','device_used','type_di','n_di','note']
        widgets = {
        'title': forms.TextInput( attrs={'class':'form-control', 'placeholder':'Title'}),
        'date': forms.DateInput(format=('%m/%d/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
        'starthour': forms.TimeInput(attrs={'class':'form-control', 'placeholder':'Start Hour', 'type':'time'}),
        'endhour': forms.TimeInput(attrs={'class':'form-control', 'placeholder':'End Hour', 'type':'time'}),

        'description': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Description', 'rows':4}),
        'equipment': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Equipment', 'rows':4}),

        'state_befor': forms.Textarea(attrs={'class':'form-control', 'placeholder':'state befor', 'rows':4}),
        'state_after': forms.Textarea(attrs={'class':'form-control', 'placeholder':'state after', 'rows':4}),

        'type_di': forms.Select(attrs={'class':'form-control', 'placeholder':'Type DI '}),
        'n_di': forms.TextInput(attrs={'class':'form-control', 'placeholder':'N° DI'}),


        'device_used': forms.Textarea(attrs={'class':'form-control', 'placeholder':'device used', 'rows':4}),
        'note': forms.Textarea(attrs={'class':'form-control', 'placeholder':'note', 'rows':4}),
    }

rapport/views.py
from rapport.forms import  RapportForm
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Rapport
from account.models import Account

def home(request):
    context = {
        'rapports': Rapport.objects.all()
    }
    return render(request, 'blog/index.html', context)


class RapportListView(ListView):
    model = Rapport
    template_name = 'rapport/rapport_list.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'objects'
    ordering = ['-id']
    paginate_by = 6


class UserRapportListView(ListView):
    model = Rapport
    template_name = 'rapport/user_rapport.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'objects'
    paginate_by = 6
    def get_queryset(self):
        user = get_object_or_404(Account, id=self.kwargs.get('pk'))
        return Rapport.objects.filter(author=user).order_by('-id')

class RapportDetailView(DetailView):
    model = Rapport



class RapportCreateView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    model = Rapport
    form_class = RapportForm
    template_name = 'rapport/rapport_form.html'
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)



class RapportUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Rapport
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        rapport = self.get_object()
        if self.request.user == rapport.author:
            return True
        return False


class RapportDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Rapport
    success_url = '/'

    def test_func(self):
        Rapport = self.get_object()
        if self.request.user == Rapport.author:
            return True
        return False


# def about(request):
#     return render(request, 'blog/about.html', {'title': 'About'})


class RapportFilterView(ListView):
    model = Rapport
    template_name = 'rapport/rapport_list.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'objects'
    ordering = ['-id']
    paginate_by = 10
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        q = self.request.GET.get('q','')
        startDate = self.request.GET.get('startdate','')
        endDate = self.request.GET.get('enddate','')

        if startDate and endDate:
            context["objects"]= Rapport.objects.filter(title__contains=q,date__range=[startDate,endDate])
        else:
            context["objects"] = Rapport.objects.filter(title__contains=q)
        context["q"] = self.request.GET.get('q','')

        return context

templates/rapport/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    {{ form|crispy}}
{% endblock content %}

templates/rapport/create_rapport.html
{% extends 'base.html' %}

{% block content %}
    Create rapport
{% endblock content %}

templates/rapport/home.html
{% extends "blog/base.html" %}
{% block content %}
    {% for post in objects %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}

templates/rapport/rapport_detail.html
{% extends "base.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        {% comment %} <a class="mr-2" href="{% url 'user-posts' object.author.username %}">{{ object.author }}</a> {% endcomment %}
        <small class="text-muted">{{ object.date|date:"F d, Y" }}</small>

        {% if object.author == user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'rapport:rapport-update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'rapport:rapport-delete' object.id %}">Delete</a>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ object.title }}</h2>
      <p class="article-content">{{ object.content }}</p>
    </div>
  </article>
{% endblock content %}

templates/rapport/rapport_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mt-5">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Rapport hebdomadaire</legend>
                 {% comment %} {{ form|crispy }} {% endcomment %}
                <div class="row">
                    <div class="col">
                        {{ form.title}}
                        {{ form.title.errors }}
                    </div>

                </div>
                <div class="row mt-3">
                     <div class="col" >
                        {{ form.date}}
                        {{ form.date.errors }}
                    </div>
                    <div class="col">
                        {{ form.starthour}}
                        {{ form.starthour.errors }}
                    </div>
                    <div class="col">
                        {{ form.endhour}}
                        {{ form.endhour.errors }}
                    </div>
                </div>

                <div class="row mt-3">
                    <div class="col">
                        {{ form.description}}
                        {{ form.description.errors }}
                    </div>
                    <div class="col">
                        {{ form.equipment}}
                        {{ form.equipment.errors }}
                    </div>
                </div>

                <div class="row mt-3">
                    <div class="col">
                        {{ form.state_befor}}
                        {{ form.state_befor.errors }}
                    </div>
                    <div class="col">
                        {{ form.state_after}}
                        {{ form.state_after.errors }}
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col">
                        {{ form.type_di}}
                        {{ form.type_di.errors }}
                    </div>
                    <div class="col">
                        {{ form.n_di}}
                        {{ form.n_di.errors }}
                    </div>
                </div>
                <div class="row mt-3">

                    <div class="col ">
                        {{ form.device_used}}
                        {{ form.device_used.errors }}
                    </div>
                    <div class="col ">
                        {{ form.note}}
                        {{ form.note.errors }}
                    </div>
                </div>

                <div class="form-group mt-3">
                    <button class="btn btn-outline-info" type="submit">Create</button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock content %}

templates/rapport/rapport_list.html
{% extends "base.html" %}
{% block content %}
    <div class="d-flex flex-row mt-4 justify-content-between  ">

        <form class="d-flex flex-row bg-white border p-3 rounded" action="{% url 'rapport:rapport-filter' %}">
          {% csrf_token %}
            <div class="d-flex flex-column">
              <div class="mx-1">
                <input type="text" name="q" class="form-control form-control-sm" palceholder="Search">
              </div>

              <div class="d-flex flex-row">
              <div class="m-1">
                <input type="date" name="startdate" class="form-control form-control-sm">
              </div>
              <div class="m-1">
                <input type="date" name="enddate" class="form-control form-control-sm">
              </div>
            </div>
            </div>
              <div class="">
                <button class="btn btn-success btn-sm ">Filter</button>
              </div>
        </form>

        <form class="d-flex flex-row bg-white border p-3 rounded" action="{% url 'rapport:rapport-excel' %}">
          {% csrf_token %}
            <div class="d-flex flex-column">

              <div class="m-1">
                <input type="date" name="startdate" class="form-control form-control-sm ">
              </div>

              <div class="mx-1">
                <input type="date" name="enddate" class="form-control form-control-sm">
              </div>

            </div>
             <div class="m-1">
                <button class="btn btn-success btn-sm ">Excel </button>
              </div>
        </form>
    </div>


    <div class=" mt-4  rounded ">
      <div class="row row-cols-1 row-cols-md-2 g-4">
    {% for post in objects %}
        <div class="col">
          <div class="card">
            <div class="card-body">
              <div class="border-bottom mb-2">
                <a class="mr-2 text-decoration-none" href="{% url 'rapport:user-rapports' post.author.id %}"> <h5>{{ post.author.first_name }}</h5></a>
                <small> {{ post.date }} {{post.starthour}} </small>
              </div>
              <h5 class="card-title">{{ post.title }}</h5>
              <p class="card-text">{{ post.date }} {{post.starthour}}</p>
              <p class="card-text">{{ post.description }}</p>
              <a href="{% url 'rapport:rapport-detail' post.id %}" class="btn btn-primary btn-sm">Read ..</a>
            </div>
          </div>
        </div>
    {% endfor %}
    </div>


      <div class="mt-4">
          {% if is_paginated %}
            {% if page_obj.has_previous %}
              <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
              <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
              {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
              {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
              {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
              <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
              <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
          {% endif %}
        </div>
      </div>

{% endblock content %}

templates/rapport/user_rapport.html
{% extends "base.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in objects %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'rapport:user-rapports' post.author.id %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'rapport:rapport-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}