account/urls.py
from django.contrib.auth import get_user
from django.urls import path
from account.views import *
from django.contrib.auth.decorators import login_required


app_name = 'account'
urlpatterns = [

    # path('', login_required(AccountHomeView.as_view()), name="account"),
    # path('security/', login_required(AccountSecurityView.as_view()) , name="account-security"),
    # path('settings/', login_required(AccountSettingsView.as_view()) , name="account-settings"),

]

project/urls.py
from account.views import login_view, logout_view, register_view
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rapport.urls')),

    path('login/', login_view , name="login"),
    path('logout/', logout_view , name="logout"),
    path('account/register/', register_view , name="register"),

]

rapport/urls.py
from rapport.excel import ToExcelFileView
from django.urls import path

from rapport.views import (
    RapportDeleteView,
    RapportDetailView,
    RapportFilterView,
    RapportListView,
    # RapportDetailView,
    RapportCreateView,
    RapportUpdateView,
    UserRapportListView,
    # RapportUpdateView,
    # RapportDeleteView,
)

app_name = 'rapport'
urlpatterns = [
    path('', RapportListView.as_view(), name='rapport-list'),
    path('user/rapports/<int:pk>', UserRapportListView.as_view(), name='user-rapports'),
    path('user/rapport/<int:pk>/', RapportListView.as_view(), name='rapport-list'),
    path('rapport/<int:pk>/', RapportDetailView.as_view(), name='rapport-detail'),
    path('rapport/create/', RapportCreateView.as_view(), name='rapport-create'),
    path('rapport/<int:pk>/update/', RapportUpdateView.as_view(), name='rapport-update'),
    path('rapport/<int:pk>/delete/', RapportDeleteView.as_view(), name='rapport-delete'),


    path('rapport/excel/', ToExcelFileView.as_view(), name='rapport-excel'),
    path('rapport/filter/', RapportFilterView.as_view(), name='rapport-filter'),
]

templates/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
         <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" >
    </head>
    <body style="background-color:#f5f5f5;">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">SBC Repport </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url 'rapport:rapport-list' %}"><i class="fas fa-list"></i> Repports</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'rapport:rapport-create' %}"><i class="fas fa-plus-circle"></i> Rapport</a>
                </li>
            </ul>

            <ul class="navbar-nav  ms-auto">
                {% if request.user.is_authenticated %}
                  <li class="nav-item">
                      <a class="btn btn-dark btn-sm  mx-2"  href="#"><i class="fas fa-lg rounded  fa-user"></i> {{ request.user.first_name }}</a>
                  </li>
                  <li class="nav-item">
                      <a class="btn btn-success btn-sm" href="{% url 'logout' %}">Logout</a>
                  </li>
                {% else %}
                  <li class="nav-item">
                      <a class="btn btn-danger" href="{% url 'login' %}">login</a>
                  </li>

                  <li class="nav-item">
                      <a class="btn btn-outline-success mx-2" href="{% url 'register' %}">Register</a>
                  </li>
                {% endif %}
              </ul>
            </div>
        </div>
    </nav>

    <main role="main" class="container">
        <div >
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        </div>

        {% block content %}{% endblock content %}
      </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    </body>
</html>